
resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger:
  branches:
    include:
    - main

variables:
- group: xmmdevops-variable-group-non-prod
- group: xmmdevops-variable-group-qa
- name: initalmodelversion
  value: initialValue
- name: finalmodelversion
  value: initialValue
- name: runid
  value: initialValue    


pool:
  vmImage: ubuntu-latest

stages:
- stage: 'RunPipline'
  variables:
  - group: xmmdevops-variable-group-non-prod
  displayName: 'TrainingPipeline'
  jobs:
  - job: "TrainingPipeline"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          addToPath: true
      - script: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install nbconvert
          pip install --upgrade azureml-core
          pip install --upgrade azureml-sdk[automl]
      

      - task: AzureCLI@1
        env:
          tenantId: $(tenantId)
          servicePrincipalId: $(servicePrincipalId)
          servicePrincipalPassword: $(servicePrincipalPassword)
          wsName: $(wsName)
          subscriptionId: $(subscriptionId)
          resourceGroup: $(resourceGroup)
          location: $(location)
        inputs:
          azureSubscription: dev-aml-workspace-connection
          scriptLocation: inlineScript
          workingDirectory: '$(Build.SourcesDirectory)'
          inlineScript: |
            echo "files:"
            ls
            az version
            az extension add -n ml -y
            az version
            az configure --defaults group=$(resourceGroup) workspace=$(wsName) location=$(location)
            
            modelversion = $(az ml model list -n mmchapter8titanic --query "[0].version" -o tsv)
            echo "##vso[task.setvariable variable=modelversion]$modelversion"
            echo "Result: $(modelversion)"

            
        displayName: 'Get Initial Model Version'
            
            
      - task: AzureCLI@1
        env:
          tenantId: $(tenantId)
          servicePrincipalId: $(servicePrincipalId)
          servicePrincipalPassword: $(servicePrincipalPassword)
          wsName: $(wsName)
          subscriptionId: $(subscriptionId)
          resourceGroup: $(resourceGroup)
          location: $(location)
        inputs:
          azureSubscription: dev-aml-workspace-connection
          scriptLocation: inlineScript
          workingDirectory: '$(Build.SourcesDirectory)'
          inlineScript: |
            echo $initalmodelversion
            run_id=$(az ml job create --file Chapter8/src/pipeline/train_and_eval_pipeline.yml --stream --query name -o tsv)
            echo run_id
        displayName: 'Training Pipeline'
            
